name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    if: contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .
          pip install ghp-import

      - name: Build HTML docs
        run: |
          cd docs
          make clean
          make html

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -f -p docs/_build/html
